version: '3.8'

services:
  db:
    environment:
      POSTGRES_USER: root
      POSTGRES_HOST_AUTH_METHOD: trust
      TZ: Asia/Tokyo
    build:
      context: ./
      dockerfile: Dockerfile.db
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./docker/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

volumes:
  db-data:
    driver: local
