version: '3.8'

services:
  db:
    environment:
      POSTGRES_USER: root
      POSTGRES_HOST_AUTH_METHOD: trust
      TZ: Asia/Tokyo
    build:
      context: ./
      dockerfile: Dockerfile.db
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./docker/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  backend:
    build: .
    command: bundle exec rails server -b 0.0.0.0
    environment:
      DATABASE_HOST: postgres
      RAILS_ENV: development
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db-data:
    driver: local
