# config/database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: graphql_ruby_backend_development
  username: graphql_ruby_backend_user
  password: <%= ENV['MY_APP_DATABASE_PASSWORD'] %>

test:
  <<: *default
  database: graphql_ruby_backend_test
  username: graphql_ruby_backend_user
  password: <%= ENV['MY_APP_DATABASE_PASSWORD'] %>

production:
  <<: *default
  database: graphql_ruby_backend_production
  username: graphql_ruby_backend_user
  password: <%= ENV['MY_APP_DATABASE_PASSWORD'] %>
