# config/database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host:     <%= ENV['DB_HOST'] || '127.0.0.1' %>
  database: <%= ENV['DB_NAME'] || 'graphql_ruby_backend_development' %>
  username: <%= ENV['DB_USERNAME'] || 'root' %>
  password: <%= ENV['DB_PASSWORD'] || '' %>

test:
  <<: *default
  host:     <%= ENV['DB_HOST'] || '127.0.0.1' %>
  database: <%= ENV['DB_NAME'] || 'graphql_ruby_backend_test' %>
  username: <%= ENV['DB_USERNAME'] || 'root' %>
  password: <%= ENV['DB_PASSWORD'] || '' %>

production:
  <<: *default
  host:     <%= ENV['DB_HOST'] %>
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
